### ISSUE TITLE
Pick a Monster button and dialog

### ISSUE THREAD

**Issue by lrbloch** [mml2222/MakingWithMonsters#10]
**if** a project is in progress
And a user is on that project's home page
**then** user sees button "Pick a Monster"

**if** a user is on that project's home page,
**When** user clicks button "Pick a Monster"
**Then** user is prompted to select a monster ("Choose the Monster you want to work with")
And the user sees an array of all the monsters they predicted
And the user sees a button labeled "Cancel"

**When** the user clicks on a monster
**Then** the user sees a button labeled "Next"

**When** the user clicks "Next"
**Then** the user sees "Use this monster to help you with your project. Come back here to share your progress!"
and the button "Cancel"

**When** the user clicks "Share Progress"
**Then** the user is prompted to upload a photo
And the user sees the button "Cancel"

**When** the user uploads a photo
**Then** the user sees the button "Submit" and the button "Cancel"

**When** the user clicks submit
**Then** the photo and monster are saved to the user's Project's Monster Moments 
And the user is redirected to their project home page

**When** the user clicks cancel
**Then** nothing is saved and the user is redirected to their project home page

**Comment by lrbloch** [comment]
@mml2222 are you ok with me working on this issue and you working on #11?
(For #11 you should complete the pull request for #5 before branching, because it will involve building off of what I've done for #5)

**Comment by mml2222** [comment]
Ok! For the upload photo, I can help you. Jin showed us how to do it last week.
